service: coeus-news-portal-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  profile: serverless
  region: eu-west-2
package:
  artifact: target/coeusnews-api-dev.jar

functions:
  coeusnews-api:
    handler: com.coeusnews.Handler
    events:
      - http:
          path: /{category}
          method: get
