service: coeus-news-portal-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  profile: serverless
  region: eu-west-2
package:
  artifact: target/hello-dev.jar

functions:
  coeusnews-api:
    handler: com.serverless.Handler
    events:
      - http:
          path: coeusnews
          method: get
