service: coeus-news-portal-backend
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  profile: serverless
  region: eu-west-2
package:
  artifact: target/coeusnews-api-dev.jar

functions:
  get-coeusnews-api:
    handler: com.coeusnews.GetCoeusnewsHandler
    events:
      - http:
          path: /{category}/coeusnews
          method: get
  save-coeusnews-api:
    handler: com.coeusnews.SaveCoeusnewsHandler
    events:
      - http:
          path: /{category}/coeusnews
          method: post
